version: '3.8'

services:

  mysql:
    container_name: mysql
    image: mysql:8.0.45
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      TZ: Asia/Shanghai
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - dev_net

  redis:
    container_name: redis
    image: redis:7.0.15
    environment:
      TZ: Asia/Shanghai
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - dev_net

  php:
    container_name: php
    build:
      context: .
      dockerfile: php/Dockerfile
    environment:
      TZ: Asia/Shanghai
    expose:
      - "9000"
    volumes:
      - ../www:/usr/share/nginx/html:delegated
    depends_on:
      - mysql
      - redis
    networks:
      - dev_net

  nginx:
    image: nginx:1.24.0
    container_name: nginx
    environment:
      TZ: Asia/Shanghai
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ../www:/usr/share/nginx/html:delegated
    ports:
      - "80:80"
    depends_on:
      - php
    networks:
      - dev_net

volumes:
  mysql_data:
  redis_data:

networks:
  dev_net:
    driver: bridge