services:

  mysql:
    image: mysql:8.0.45
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      TZ: Asia/Shanghai
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - dev_net

  redis:
    image: redis:7.0.15
    environment:
      TZ: Asia/Shanghai
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - dev_net

  core:
    build:
      context: php
      dockerfile: Dockerfile
    environment:
      TZ: Asia/Shanghai
      PHP_IDE_CONFIG: "serverName=core.test"
    user: "${UID:-1000}:${GID:-1000}"
    expose:
      - "9000"
    volumes:
      - ${PROJECT_ROOT}/core:/usr/share/nginx/html/core:cached
    networks:
      - dev_net
    working_dir: /usr/share/nginx/html/core

  oms:
    build:
      context: php
      dockerfile: Dockerfile
    environment:
      TZ: Asia/Shanghai
      PHP_IDE_CONFIG: "serverName=oms.test"
    user: "${UID:-1000}:${GID:-1000}"
    expose:
      - "9000"
    volumes:
      - ${PROJECT_ROOT}/oms:/usr/share/nginx/html/oms:cached
    networks:
      - dev_net
    working_dir: /usr/share/nginx/html/oms

  wms:
    build:
      context: php
      dockerfile: Dockerfile
    environment:
      TZ: Asia/Shanghai
      PHP_IDE_CONFIG: "serverName=wms.test"
    user: "${UID:-1000}:${GID:-1000}"
    expose:
      - "9000"
    volumes:
      - ${PROJECT_ROOT}/wms:/usr/share/nginx/html/wms:cached
    networks:
      - dev_net
    working_dir: /usr/share/nginx/html/wms

  pms:
    build:
      context: php
      dockerfile: Dockerfile
    environment:
      TZ: Asia/Shanghai
      PHP_IDE_CONFIG: "serverName=pms.test"
    user: "${UID:-1000}:${GID:-1000}"
    expose:
      - "9000"
    volumes:
      - ${PROJECT_ROOT}/pms:/usr/share/nginx/html/pms:cached
    networks:
      - dev_net
    working_dir: /usr/share/nginx/html/pms

  nginx:
    image: nginx:1.24.0
    environment:
      TZ: Asia/Shanghai
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ${PROJECT_ROOT}:/usr/share/nginx/html:cached
    ports:
      - "80:80"
    networks:
      dev_net:
        aliases:
          - core.test
          - oms.test
          - wms.test
          - pms.test

volumes:
  mysql_data:
  redis_data:

networks:
  dev_net:
    driver: bridge